---
- name: Install Jenkins, Maven and Git on Jenkins Server
  hosts: jenkins
  become: yes

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Java
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Maven
      yum:
        name: maven
        state: present

    - name: Install Git
      yum:
        name: git
        state: present
